apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        hosts {
         192.168.99.100 minikube.local minikube
         fallthrough
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
